### ISSUE TITLE
Error "partial modifier can only appear before ..." when the class is 'sealed'

### ISSUE THREAD

**Issue by CodeSmile-0000011110110111** [LurkingNinja/com.lurking-ninja.dependency#3]
I get this error:

`SourceGenerator\LurkingNinja.SourceGenerator.DiSourceGenerator\WeaponDev_codegen.cs(12,12): error CS0267: The 'partial' modifier can only appear immediately before 'class', 'record', 'struct', 'interface', or a method return type.
`

With this class:

```
using LurkingNinja.Attributes;
using UnityEditor;
using UnityEngine;

namespace CodeSmile.MultiPal.Weapons
{
	[ExecuteInEditMode]
	[DisallowMultipleComponent]
	[RequireComponent(typeof(WeaponSetup))]
	[GenerateOnValidate]
	public sealed partial class WeaponDev : MonoBehaviour
	{
		[Get] [InjectInEditor] [SerializeField] private WeaponSetup m_WeaponSetup;
	}
}
```

The error goes away by removing the 'sealed' keyword. I suppose codegen generates this as `public partial sealed class`.

**Comment by LurkingNinjaDev** [comment]
See [Changelog](https://github.com/LurkingNinja/com.lurking-ninja.dependency/blob/main/CHANGELOG.md#010---2024-10-26)
