### ISSUE TITLE
InitializeInEditor() method name is generic, obscures its purpose

### ISSUE THREAD

**Issue by CodeSmile-0000011110110111** [LurkingNinja/com.lurking-ninja.dependency#5]
"InitializeInEditor" doesn't say what it is initializing or why. There's nothing hinting at this being part of the DI system.

I would prefer the method be called `InjectReferencesInEditor` and likewise `InjectReferencesAtRuntime`.

**Comment by LurkingNinjaDev** [comment]
Next I will work on this package a little in the immediate future, will take a look! Thanks for the feedback!

**Comment by LurkingNinjaDev** [comment]
See [Changelog](https://github.com/LurkingNinja/com.lurking-ninja.dependency/blob/main/CHANGELOG.md#010---2024-10-26)
